### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by maxwowpow** [peterblazejewicz/mdl-templates-asp5-mvc6#1]
Steps described followed.
Running the Website with beta7 and rc1 (x64 and x86) causes:

System.InvalidOperationException: No service for type 'Microsoft.Dnx.Runtime.IApplicationEnvironment' has been registered.

Running from console, not from Visual Studio.

**Comment by peterblazejewicz** [comment]
@maxgrass 
Let me update this to RC1 (could be one-by-one).
Thanks!

**Comment by peterblazejewicz** [comment]
@maxgrass 
Updated. Thanks!
